#!/bin/bash

echo " enter the name to check "
read name

if [ -L $name ];
then
        echo " $name is soft link "
elif [ -d $name ];
then
        echo " $name is dire "
	ls -lrt $name
elif [ -f $name ];
then
        echo " $name is file "
	cat $name
       	echo " number of lines in $name is " 
	cat $name | wc -l 	
else
        echo " $name not exist "
fi

#echo " girish "
