#!/bin/bash

echo " enter the name to check "
read name

if [ -f $name ];
then
	echo " $name is file "
elif [ -d $name ];
then
	echo " $name is dire "
elif [ -L $name ];
then
	echo " $name is link"	
else
	echo " $name not exist "
fi
